CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Car = CarRental.Entity.Concretes.Car;
using CarRental.BusinessLogic.Concretes;

namespace CarRental.AspNetWeb.Pure.Controllers
{
    public class CarController : Controller
    {

        // GET: Car
        public ActionResult Index()
        {
            return View();
        }


        // GET: Car/Details/1
        public ActionResult Details(int id)
        {
            return View(SelectCarByID(id));
        }


        // GET: Car/Create
        public ActionResult Create()
        {
            return View();
        }


        public ActionResult Rent()
        {
            return View();
        }


        // POST: Car/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (InsertCar(collection["CarName"], int.Parse(collection["CarModel"]), int.Parse(collection["RentFeeDaily"]), int.Parse(collection["CarTotalKM"]), int.Parse(collection["CarTotalSeats"]), int.Parse(collection["CompanyID"]) ))
                    return RedirectToAction("ListAll");

                return View();
            }
            catch (Exception ex)
            {
                // LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("AspNetWeb.Pure::CarController::CreateCar::Error occured.", ex);
                //return View();
            }
        }


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        /*public ActionResult Rent(FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (Rent(collection["CarName"], int.Parse(collection["CarModel"]), int.Parse(collection["RentFeeDaily"]), int.Parse(collection["CarTotalKM"]), int.Parse(collection["CarTotalSeats"]), int.Parse(collection["CompanyID"])))
                    return RedirectToAction("ListAll");

                return View();
            }
            catch (Exception ex)
            {
                // LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("AspNetWeb.Pure::CarController::CreateCar::Error occured.", ex);
                //return View();
            }
        }*/
        public ActionResult RentCar()
        {
            try
            {
              Car car = SelectCarByID(int.Parse(Request.Form["aracID"]));
              Rent(car.CarID, car.CarName, car.CarModel, car.RentFeeDaily, car.CarTotalKM, car.CarTotalSeats, car.CompanyID);
                IList<Car> cars = ListAllCars().ToList();
                return View("ListAll", cars);
            }
            catch (Exception ex)
            {

                throw new Exception("hata oldu la", ex);
            }
        }

        // GET: Car/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(SelectCarByID(id));
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        // POST: Car/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (UpdateCar(id, collection["CarName"], int.Parse(collection["CarModel"]), int.Parse(collection["RentFeeDaily"]), int.Parse(collection["CarTotalKM"]), int.Parse(collection["CarTotalSeats"]), int.Parse(collection["CompanyID"])))
                    return RedirectToAction("Index");

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Car/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                if (DeleteCar(id))
                    return RedirectToAction("ListAll");
                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Operation failed!", ex);
            }
        }

        public ActionResult ListAll()
        {
            try
            {
                IList<Car> cars = ListAllCars().ToList();
                return View(cars);
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        #region PRIVATE METHODS

        private bool InsertCar(string name, int model, int rentFee, int totalKM, int totalSeats, int companyID)
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    return carBussines.InsertCar(new Car()
                    {
                        CarName = name,
                        CarModel = model,
                        RentFeeDaily = rentFee,
                        CarTotalKM = totalKM,
                        CarTotalSeats = totalSeats,
                        CompanyID= companyID
                    });
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        private bool Rent(int ID ,string name, int model, int rentFee, int totalKM, int totalSeats, int companyID)
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    return carBussines.Rent(new Car()
                    {
                        CarID = ID,
                        CarName = name,
                        CarModel = model,
                        RentFeeDaily = rentFee,
                        CarTotalKM = totalKM,
                        CarTotalSeats = totalSeats,
                        CompanyID = companyID
                    });
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        private bool UpdateCar(int id, string name, int model, int rentFee, int totalKM, int totalSeats, int companyID)
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    return carBussines.UpdateCar(new Car()
                    {
                        CarID = id,
                        CarName = name,
                        CarModel = model,
                        RentFeeDaily = rentFee,
                        CarTotalKM = totalKM,
                        CarTotalSeats = totalSeats,
                        CompanyID = companyID
                    });
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        private bool DeleteCar(int ID)
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    return carBussines.DeleteCarById(ID);
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        public List<Car> ListAllCars()
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    List<Car> cars = carBussines.SelectAllCars();
                    return cars;
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        private Car SelectCarByID(int ID)
        {
            try
            {
                using (var carBussines = new CarBusiness())
                {
                    return carBussines.SelectCarById(ID);
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Car doesn't exists.", ex);
            }
        }

        #endregion

    }
}

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Customer = CarRental.Entity.Concretes.Customer;
using CarRental.BusinessLogic.Concretes;

namespace CarRental.AspNetWeb.Pure.Controllers
{
    public class CustomerController : Controller
    {

        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }


        // GET: Customer/Details/5
        public ActionResult Details(int id)
        {
            return View(SelectCustomerByID(id));
        }


        // GET: Customer/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Customer/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (InsertCustomer(collection["CustomerName"], collection["CustomerSurname"], collection["PhoneNumber"], collection["Email"]))
                    return RedirectToAction("ListAll");

                return View();
            }
            catch (Exception ex)
            {
                // LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("AspNetWeb.Pure::CustomerController::CreateCustomer::Error occured.", ex);
                //return View();
            }
        }



        // GET: Customer/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                return View(SelectCustomerByID(id));
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        // POST: Customer/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                if (UpdateCustomer(id, collection["CustomerName"], collection["CustomerSurname"], collection["PhoneNumber"], collection["Email"]))
                    return RedirectToAction("Index");

                return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: Customer/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                if (DeleteCustomer(id))
                    return RedirectToAction("ListAll");
                return RedirectToAction("ListAll");
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Operation failed!", ex);
            }
        }

        public ActionResult ListAll()
        {
            try
            {
                IList<Customer> customers = ListAllCustomers().ToList();
                return View(customers);
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        #region PRIVATE METHODS

        private bool InsertCustomer(string name, string surname, string number, string email)
        {
            try
            {
                using (var customerBussines = new CustomerBusiness())
                {
                    return customerBussines.InsertCustomer(new Customer()
                    {
                        CustomerName = name,
                        CustomerSurname = surname,
                        PhoneNumber = number,
                        Email = email
                    });
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        private bool UpdateCustomer(int id, string name, string surname, string number, string email)
        {
            try
            {
                using (var customerBussines = new CustomerBusiness())
                {
                    return customerBussines.UpdateCustomer(new Customer()
                    {
                        CustomerID = id,
                        CustomerName = name,
                        CustomerSurname = surname,
                        PhoneNumber = number,
                        Email = email
                    });
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        private bool DeleteCustomer(int ID)
        {
            try
            {
                using (var customerBussines = new CustomerBusiness())
                {
                    return customerBussines.DeleteCustomerById(ID);
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        private List<Customer> ListAllCustomers()
        {
            try
            {
                using (var customerBussines = new CustomerBusiness())
                {
                    List<Customer> customers = customerBussines.SelectAllCustomers();
                    return customers;
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        private Customer SelectCustomerByID(int ID)
        {
            try
            {
                using (var customerBussines = new CustomerBusiness())
                {
                    return customerBussines.SelectCustomerById(ID);
                }
            }
            catch (Exception ex)
            {
                //LogHelper.Log(LogTarget.File, ExceptionHelper.ExceptionToString(ex), true);
                throw new Exception("Customer doesn't exists.", ex);
            }
        }

        #endregion














    }
}

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Views/Customer/Create.cshtml
@model CarRental.Entity.Concretes.Customer

@{ ViewBag.Title = "Create Customer"; }

<h2>@ViewBag.Title</h2>



<div class="loginbox">
    @using (Html.BeginForm())
    {
@Html.AntiForgeryToken()

                <form class="ArabaKayit" method="post">
                    <h1>Müşteri Kayıt Formu </h1>

                    <p>Müşteri İsmi</p>
                    <input type="text" name="CustomerName" /> <br />
                    <p>Müşteri Soyismi</p>
                    <input type="text" name="CustomerSurname" /> <br />
                    <p>Telefon No </p>
                    <input type="text"  name="PhoneNumber" /> <br />
                    <p> E Mail</p>
                    <input type="text"  name="Email" />  <br />
                    <button type="submit" class="btnKullanici2">Müşteri Kaydet</button>




                </form>}

</div>


<div>
    @Html.ActionLink("Back to List of Customers", "ListAll")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Views/Customer/Details.cshtml
@using System.Activities.Statements
@using System.Runtime.Remoting.Messaging
@model CarRental.Entity.Concretes.Customer

@{ ViewBag.Title = "Details"; }

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CustomerName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CustomerSurname)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CustomerSurname)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<div>
    <h4>Rent Infos</h4>
    <hr />
    @foreach (var item in Model.RentInfos)
    {
<dl class="dl-horizontal">
    <dt>
        @Html.Raw("Rent Infos")
    </dt>

    <dt>
        @Html.Raw("Rent Dates:")
    </dt>

 
</dl>}
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerID }) |
    @Html.ActionLink("Back to List", "ListAll")
</p>

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Views/Customer/Edit.cshtml
@model CarRental.Entity.Concretes.Customer
@{ ViewBag.Title = "Edit Customer"; }

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
@Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.CustomerID)

                    <div class="form-group">
                        @Html.LabelFor(model => model.CustomerName, "Customer Name", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CustomerSurname, "Customer Surname", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CustomerSurname, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.CustomerSurname, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, "Phone Number", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Email, "Email", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Save" class="btn btn-default" />
                        </div>
                    </div>
                </div>}

<div>
    @Html.ActionLink("Back to List of Customer", "ListAll")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Views/Customer/ListAll.cshtml
@model IEnumerable<CarRental.Entity.Concretes.Customer>

@{ ViewBag.Title = "All Customers"; }

<h2>@ViewBag.Title</h2>



    <table class="table">
        <tr>

            <th>@Html.Encode("Customer Name")</th>
            <th>@Html.Encode("Customer Surname")</th>
            <th>@Html.Encode("Phone Nummber")</th>
            <th> @Html.Encode("Email")</th>
        </tr>

      

           
       




        @foreach (var item in Model)
        {
    <tr>

        <td>@Html.DisplayFor(modelItem => item.CustomerName)</td>
        <td>@Html.DisplayFor(modelItem => item.CustomerSurname)</td>
        <td>@Html.DisplayFor(modelItem => item.PhoneNumber)</td>
        <td>@Html.DisplayFor(modelItem => item.Email) </td>
        <td>
            @Html.ActionLink("Detail", "Details", new { id = item.CustomerID }) |
            @Html.ActionLink("Edit", "Edit", new { id = item.CustomerID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.CustomerID })
        </td>




    </tr>

    



                  
                              
                                            
}

    @Html.ActionLink("Create New", "Create")
    </table>
    
   

CarRentalSystem-master/CarRentalSystem-master/CarRentalSystem-master/CarRental/CarRental.AspNetWeb.Pure/Views/Customer/Login.cshtml
@{ ViewBag.Title = "Login"; }


<div class="loginbox">

    <form class="MusteriLogin" method="post">
        <h1>Kullanıcı Giriş Formu </h1>

        <p>Kullanıcı İsmi</p>
        <input type="text" name="Customer Name" id="ad" /> <br />
        <p>Kullanıcı Şifresi</p>
        <input type="text" name="Customer Surname" id="sifre" /> <br />

        <button type="submit" id="btnGiris">@Html.ActionLink("Giriş Yap", "ListAll", "Car")</button>
        <button type="submit" class="btnKayt">@Html.ActionLink("Kayıt ol", "Create", "Customer")</button>




    </form>
</div>